context:
  name: tryton
  version: 3.6.7

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/tryton/tryton/archive/refs/tags/tryton-${{ version }}.tar.gz
  sha256: aa6aade3e5b6d808ee69d2af537d359372670153faa2b8ba6c3a7469271bf024

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=2.7,<2.8
    - setuptools
  run:
    - python >=2.7,<2.8
    - cairo >=1.16,<1.17
    - python-dateutil
    - pygobject <=3.44,<3.45
    - gtk3
    - librsvg

tests:
  - python:
      imports:
        - tryton
      pip_check: true

about:
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Tryton is business software, ideal for companies of any size, easy to use, complete and 100% Open Source.
  homepage: https://www.tryton.org/
  repository: https://github.com/tryton/tryton

extra:
  recipe-maintainers:
    - looooo
