context:
  name: tryton
  version: "7.6.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/tryton/tryton/archive/refs/tags/tryton-${{ version }}.tar.gz
  sha256: af1a2021dbea4564de7cf30136571555f4b651a6087740cf6e4479fd3f80181e
  patches:
    - patches/python313.patch
    - patches/entry_points.patch

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install ./tryton --no-deps -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - cairo
    - python-dateutil
    - pygobject
    - gtk3
    - librsvg

tests:
  - python:
      imports:
        - tryton
      pip_check: true

about:
  license: GPL-3.0-or-later
  license_file: tryton/COPYRIGHT
  summary: Tryton is business software, ideal for companies of any size, easy to use, complete and 100% Open Source.
  homepage: https://www.tryton.org/
  repository: https://github.com/tryton/tryton

extra:
  recipe-maintainers:
    - looooo
